//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcheggio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingHistory
    {
        public long IDStorico { get; set; }
        public string Targa { get; set; }
        public System.DateTime DataOrarioEntrata { get; set; }
        public System.DateTime DataOrarioUscita { get; set; }
        public double Tariffa { get; set; }
        public string Riga { get; set; }
        public string Colonna { get; set; }
        public string TipoVeicolo { get; set; }
        public string NomeParcheggio { get; set; }
        public string Propietario { get; set; }
    
        public virtual ParkingCost ParkingCost { get; set; }
        public virtual Parking Parking { get; set; }
        public virtual Person Person { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
