//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcheggio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingAmount
    {
        public System.DateTime Giorno { get; set; }
        public string IncassoTotale { get; set; }
        public string NomeParcheggio { get; set; }
    
        public virtual Parking Parking { get; set; }
    }
}
